#!/usr/bin/env -S bash -e
export VOLUME=${1:-/tmp/volume1/}
export TYPE=volume
export PORT=${PORT:-3001}

mkdir -p $VOLUME
chmod 777 $VOLUME

CONF=$(mktemp)
echo "
daemon off;
worker_processes auto;
pcre_jit on;

error_log /dev/stderr warn;
pid $VOLUME/nginx.pid;

events {
  multi_accept on;
  accept_mutex off;
  worker_connections 4096;
}

http {
  sendfile on;

  tcp_nopush on;
  tcp_nodelay on;

  open_file_cache off;
  types_hash_max_size 2048;

  server_tokens off;

  default_type application/octet-stream;

  access_log /dev/stdout;

  server {
    listen $PORT default_server backlog=4096;

    # we don't expect any large files
    client_max_body_size 16m;
    client_body_buffer_size 16m;
    client_body_temp_path $VOLUME/tmp;

    location / {
      root $VOLUME;
      disable_symlinks on;

      dav_methods PUT DELETE;
      dav_access group:rw all:r;
      create_full_put_path on;

      autoindex on;
      autoindex_format json;
    }
  }
}" > $CONF
echo "starting nginx on $PORT with config $CONF"
nginx -c $CONF -p $VOLUME/tmp

